### ISSUE TITLE
Trying to run PSFj from command line

### ISSUE THREAD

**Issue by malj390** [cmongis/psfj#5]
Hello, I started running jar files from the command line recently so I'm wondering if I did something wrong here.
The parameters are provided in the .ini file. And example.tif is just a Z stack with 1 channel.
I would like to run it without the GUI if possible.

```
java -jar psfj.jar -i "example.tif" -c "example.ini" -d -o "results.csv"
-i
example.tif
-c
example.ini
-d
-o
results.csv
example.ini
Loading example.tif...
java.lang.NullPointerException
        at knop.psfj.BeadImage.setImageFolder(BeadImage.java:474)
        at knop.psfj.BeadImage.setFileAddress(BeadImage.java:801)
        at knop.psfj.BeadImage.<init>(BeadImage.java:346)
        at PSFj.main(PSFj.java:124)
```

I tried to follow the flags described in the --help command.

```
--help
usage: psfj
 -2c,--dual-channel <arg>          multichannel analysis with the
                                   specified file (INI file mandatory)
 -3d,--3-dimensional               use 3D Object detection algorithm for
                                   bead detection
 -a,--all                          exports all above
 -c,--calibration <arg>            calibration file .ini (optional) : if a
                                   file contains the same name as the
                                   image with the .ini extension, it will
                                   be loaded as the image calibration file
 -d,--csv                          exports data as csv
 -f,--fill-report <arg>            compile informations in a file in the
                                   export folder
 -g,--generate-calibration <arg>   generates a typical calibration file
 -h,--help                         displays help
 -i,--input <arg>                  input file
 -m,--heatmap                      exports heatmap
 -o,--output <arg>                 output directory (optional)  : if not
                                   specified,
 -r,--bead-report                  exports bead PSF Reports
 -s,--sum-up                       exports PDF Summary
 -v,--version                      displays PSFj version
 -w,--bead-frame <arg>             bead frame of with a size of N times
                                   the expected FWHM
```

Thank you

**Comment by malj390** [comment]
Just realized I needed to put the full path to all the files. But still getting this error.

```
Loading image in memory...
log4j:WARN No appenders could be found for logger (loci.common.NIOByteBufferProvider).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at loci.common.DataTools.makeDataArray(DataTools.java:567)
        at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:215)
        at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:87)
        at knop.psfj.BeadImage.workFromMemory(BeadImage.java:704)
        at PSFj.main(PSFj.java:134)
```

**Comment by malj390** [comment]
Fixed it by adding the java flag for memory usage -Xmx
I also added the summary report flag -s
```
java -Dlog4j -Xmx1000m -jar psfj.jar -i "C:\fullpath\to\example.tif" -s -o "C:\fullpath\to\\results"
```

Still the Dlog4j warning appears but it generates the same summary report than done with the GUI, so I guess it's ok.

**Comment by cmongis** [comment]
Hi!

Did you try to put the absolute path of the file?

Cheers,

Cyril

**Comment by malj390** [comment]
It is already working. Thanks @cmongis
